### ISSUE TITLE
About Web And above

### ISSUE THREAD

**Issue by canbaran011** [FezVrasta/ama#7]
Hi @FezVrasta, I'd like to ask you...
  I am a computer engineering student and i want to know how can i improve my skills on frontend and backend division on this sector. I am mid-level in html ,  css and javascript. I think that i should work more javascript. Then i would love to hear what can i do for backend side ? For example How can i learn NodeJS properly for my future. ( I know that i dont know much about backend vs. but i want to learn). Which books can you offer me either frontend and backend. Should I learn PHP ? May the my qquestions could be has the lack of something . But i am sure that you can guide me in a true way.
THANK YOU !

**Comment by FezVrasta** [comment]
Hi @canbaran011!

To improve in JavaScript I would suggest you to look into React, I know it may seem biased, but really, since I started to work with it my skill increased greatly. It forces you to think in a certain way that helps to make your code simple and easy to maintain.

About Node.js, I don't program with it often so I'm not quite updated about the latest trends.

PHP... I would avoid it honestly, there are quite some companies that still use it, but most of them have legacy code-bases that I wouldn't like to work on as my daily job. You should work on something cool that you like and that will allow you to learn something you'll be able to use in your next job.

About books, I'm sorry but I never read a programming book in my life, I can suggest you The Hitchhiker's Guide to the Galaxy if you want to read a good book tho 😉
